version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: "database"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4a8cd0fd1